### List all messages

GEt http://localhost:3000/messages

### Create a new messages
POST http://localhost:3000/messages
content-type: application/json

{
  "content":"new content"
}


### Get a particular message
GET http://localhost:3000/messages/444